INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('A# .NET', 'https://en.wikipedia.org/wiki/A_Sharp_(.NET)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('A# (Axiom)', 'https://en.wikipedia.org/wiki/A_Sharp_(Axiom)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('A-0 System', 'https://en.wikipedia.org/wiki/A-0_System');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('A+', 'https://en.wikipedia.org/wiki/A%2B_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('A++', 'https://en.wikipedia.org/wiki/A%2B%2B');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ABAP', 'https://en.wikipedia.org/wiki/ABAP');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ABC', 'https://en.wikipedia.org/wiki/ABC_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ABC ALGOL', 'https://en.wikipedia.org/wiki/ABC_ALGOL');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ABSET', 'https://en.wikipedia.org/wiki/ABSET');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ABSYS', 'https://en.wikipedia.org/wiki/ABSYS');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ACC', 'https://en.wikipedia.org/wiki/ACC_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Accent', 'https://en.wikipedia.org/wiki/Accent_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Ace DASL', 'https://en.wikipedia.org/wiki/Distributed_Application_Specification_Language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ACL2', 'https://en.wikipedia.org/wiki/ACL2');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ACT-III', 'https://en.wikipedia.org/wiki/LGP-30#ACT-III_programming_language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Action!', 'https://en.wikipedia.org/wiki/Action!_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ActionScript', 'https://en.wikipedia.org/wiki/ActionScript');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Ada', 'https://en.wikipedia.org/wiki/Ada_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Adenine', 'https://en.wikipedia.org/wiki/Adenine_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Agda', 'https://en.wikipedia.org/wiki/Agda_(theorem_prover)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Agilent VEE', 'https://en.wikipedia.org/wiki/Agilent_VEE');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Agora', 'https://en.wikipedia.org/wiki/Agora_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('AIMMS', 'https://en.wikipedia.org/wiki/AIMMS');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Alef', 'https://en.wikipedia.org/wiki/Alef_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ALF', 'https://en.wikipedia.org/wiki/Algebraic_Logic_Functional_programming_language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ALGOL 58', 'https://en.wikipedia.org/wiki/ALGOL_58');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ALGOL 60', 'https://en.wikipedia.org/wiki/ALGOL_60');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ALGOL 68', 'https://en.wikipedia.org/wiki/ALGOL_68');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ALGOL W', 'https://en.wikipedia.org/wiki/ALGOL_W');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Alice', 'https://en.wikipedia.org/wiki/Alice_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Alma-0', 'https://en.wikipedia.org/wiki/Alma-0');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('AmbientTalk', 'https://en.wikipedia.org/wiki/AmbientTalk');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Amiga E', 'https://en.wikipedia.org/wiki/Amiga_E');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('AMOS', 'https://en.wikipedia.org/wiki/AMOS_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('AMPL', 'https://en.wikipedia.org/wiki/AMPL');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Apex (Salesforce.com)', 'https://en.wikipedia.org/wiki/Salesforce.com#Apex');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('APL', 'https://en.wikipedia.org/wiki/APL_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('App Inventor for Android''s visual block language', 'https://en.wikipedia.org/wiki/App_Inventor_for_Android_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('AppleScript', 'https://en.wikipedia.org/wiki/AppleScript');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Arc', 'https://en.wikipedia.org/wiki/Arc_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ARexx', 'https://en.wikipedia.org/wiki/ARexx');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Argus', 'https://en.wikipedia.org/wiki/Argus_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('AspectJ', 'https://en.wikipedia.org/wiki/AspectJ');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Assembly language', 'https://en.wikipedia.org/wiki/Assembly_language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ATS', 'https://en.wikipedia.org/wiki/ATS_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Ateji PX', 'https://en.wikipedia.org/wiki/Ateji_PX');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('AutoHotkey', 'https://en.wikipedia.org/wiki/AutoHotkey');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Autocoder', 'https://en.wikipedia.org/wiki/Autocoder');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('AutoIt', 'https://en.wikipedia.org/wiki/AutoIt');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('AutoLISP / Visual LISP', 'https://en.wikipedia.org/wiki/AutoLISP');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Averest', 'https://en.wikipedia.org/wiki/Averest');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('AWK', 'https://en.wikipedia.org/wiki/AWK');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Axum', 'https://en.wikipedia.org/wiki/Axum_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('B', 'https://en.wikipedia.org/wiki/B_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Babbage', 'https://en.wikipedia.org/wiki/Babbage_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Bash', 'https://en.wikipedia.org/wiki/Bash_(Unix_shell)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('BASIC', 'https://en.wikipedia.org/wiki/BASIC');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('bc', 'https://en.wikipedia.org/wiki/Bc_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('BCPL', 'https://en.wikipedia.org/wiki/BCPL');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('BeanShell', 'https://en.wikipedia.org/wiki/BeanShell');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Batch (Windows/Dos)', 'https://en.wikipedia.org/wiki/Batch_file');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Bertrand', 'https://en.wikipedia.org/wiki/Bertrand_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('BETA', 'https://en.wikipedia.org/wiki/BETA_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Bigwig', 'https://en.wikipedia.org/wiki/Bigwig_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Bistro', 'https://en.wikipedia.org/wiki/Bistro_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('BitC', 'https://en.wikipedia.org/wiki/BitC');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('BLISS', 'https://en.wikipedia.org/wiki/BLISS_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Blockly', 'https://en.wikipedia.org/wiki/Blockly');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('BlooP', 'https://en.wikipedia.org/wiki/BlooP_and_FlooP');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Blue', 'https://en.wikipedia.org/wiki/Blue_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Boo', 'https://en.wikipedia.org/wiki/Boo_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Boomerang', 'https://en.wikipedia.org/wiki/Boomerang_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Bourne shell (including', 'https://en.wikipedia.org/wiki/Bourne_shell');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('bash and', 'https://en.wikipedia.org/wiki/Bash_(Unix_shell)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ksh )', 'https://en.wikipedia.org/wiki/Korn_shell');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('BREW', 'https://en.wikipedia.org/wiki/Qualcomm_Brew');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('BPEL', 'https://en.wikipedia.org/wiki/Business_Process_Execution_Language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('C', 'https://en.wikipedia.org/wiki/C_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('C--', 'https://en.wikipedia.org/wiki/C--');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('C/AL', 'https://en.wikipedia.org/wiki/C/AL');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Caché ObjectScript', 'https://en.wikipedia.org/wiki/Cach%C3%A9_ObjectScript');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('C Shell', 'https://en.wikipedia.org/wiki/C_Shell');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Caml', 'https://en.wikipedia.org/wiki/Caml');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Cayenne', 'https://en.wikipedia.org/wiki/Cayenne_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('CDuce', 'https://en.wikipedia.org/wiki/CDuce');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Cecil', 'https://en.wikipedia.org/wiki/Cecil_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Cel', 'https://en.wikipedia.org/wiki/Cel_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Cesil', 'https://en.wikipedia.org/wiki/Cesil');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Ceylon', 'https://en.wikipedia.org/wiki/Ceylon_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('CFEngine', 'https://en.wikipedia.org/wiki/CFEngine');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('CFML', 'https://en.wikipedia.org/wiki/ColdFusion_Markup_Language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Cg', 'https://en.wikipedia.org/wiki/Cg_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Ch', 'https://en.wikipedia.org/wiki/Ch_(computer_programming)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Chapel', 'https://en.wikipedia.org/wiki/Chapel_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('CHAIN', 'https://en.wikipedia.org/wiki/CHAIN_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Charity', 'https://en.wikipedia.org/wiki/Charity_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Charm', 'https://en.wikipedia.org/wiki/Charm_(language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Chef', 'https://en.wikipedia.org/wiki/Chef_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('CHILL', 'https://en.wikipedia.org/wiki/CHILL');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('CHIP-8', 'https://en.wikipedia.org/wiki/CHIP-8');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('chomski', 'https://en.wikipedia.org/wiki/Chomski');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ChucK', 'https://en.wikipedia.org/wiki/ChucK');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('CICS', 'https://en.wikipedia.org/wiki/CICS');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Cilk', 'https://en.wikipedia.org/wiki/Cilk');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Citrine (programming language)', 'https://en.wikipedia.org/wiki/Citrine_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('CL (IBM)', 'https://en.wikipedia.org/wiki/AS/400_Control_Language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Claire', 'https://en.wikipedia.org/wiki/Claire_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Clarion', 'https://en.wikipedia.org/wiki/Clarion_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Clean', 'https://en.wikipedia.org/wiki/Clean_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Clipper', 'https://en.wikipedia.org/wiki/Clipper_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('CLIST', 'https://en.wikipedia.org/wiki/CLIST');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Clojure', 'https://en.wikipedia.org/wiki/Clojure');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('CLU', 'https://en.wikipedia.org/wiki/CLU_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('CMS-2', 'https://en.wikipedia.org/wiki/CMS-2_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('COBOL – ISO/IEC 1989', 'https://en.wikipedia.org/wiki/COBOL');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Cobra', 'https://en.wikipedia.org/wiki/Cobra_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('CODE', 'https://en.wikipedia.org/wiki/CODE_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('CoffeeScript', 'https://en.wikipedia.org/wiki/CoffeeScript');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ColdFusion', 'https://en.wikipedia.org/wiki/ColdFusion');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('COMAL', 'https://en.wikipedia.org/wiki/COMAL');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Combined Programming Language (CPL)', 'https://en.wikipedia.org/wiki/Combined_Programming_Language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('COMIT', 'https://en.wikipedia.org/wiki/COMIT');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Common Intermediate Language (CIL)', 'https://en.wikipedia.org/wiki/Common_Intermediate_Language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Common Lisp (also known as CL)', 'https://en.wikipedia.org/wiki/Common_Lisp');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('COMPASS', 'https://en.wikipedia.org/wiki/COMPASS');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Component Pascal', 'https://en.wikipedia.org/wiki/Component_Pascal');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Constraint Handling Rules (CHR)', 'https://en.wikipedia.org/wiki/Constraint_Handling_Rules');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Converge', 'https://en.wikipedia.org/wiki/Converge_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Cool', 'https://en.wikipedia.org/wiki/Cool_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Coq', 'https://en.wikipedia.org/wiki/Coq');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Coral 66', 'https://en.wikipedia.org/wiki/Coral_66');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Corn', 'https://en.wikipedia.org/wiki/Corn_(emulator)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('CorVision', 'https://en.wikipedia.org/wiki/CorVision');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('COWSEL', 'https://en.wikipedia.org/wiki/COWSEL');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('CPL', 'https://en.wikipedia.org/wiki/Combined_Programming_Language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Cryptol', 'https://en.wikipedia.org/wiki/Cryptol');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('csh', 'https://en.wikipedia.org/wiki/C_shell');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Csound', 'https://en.wikipedia.org/wiki/Csound');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('CSP', 'https://en.wikipedia.org/wiki/Communicating_sequential_processes');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('CUDA', 'https://en.wikipedia.org/wiki/CUDA');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Curl', 'https://en.wikipedia.org/wiki/Curl_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Curry', 'https://en.wikipedia.org/wiki/Curry_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Cyclone', 'https://en.wikipedia.org/wiki/Cyclone_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Cython', 'https://en.wikipedia.org/wiki/Cython');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('D', 'https://en.wikipedia.org/wiki/D_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('DASL (Datapoint''s Advanced Systems Language)', 'https://en.wikipedia.org/wiki/Datapoint%27s_Advanced_Systems_Language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('DASL (Distributed Application Specification Language)', 'https://en.wikipedia.org/wiki/Distributed_Application_Specification_Language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Dart', 'https://en.wikipedia.org/wiki/Dart_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('DataFlex', 'https://en.wikipedia.org/wiki/DataFlex');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Datalog', 'https://en.wikipedia.org/wiki/Datalog');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('DATATRIEVE', 'https://en.wikipedia.org/wiki/DATATRIEVE');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('dBase', 'https://en.wikipedia.org/wiki/DBase');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('dc', 'https://en.wikipedia.org/wiki/Dc_(computer_program)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('DCL', 'https://en.wikipedia.org/wiki/DIGITAL_Command_Language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Deesel (formerly G)', 'https://en.wikipedia.org/wiki/Deesel');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Delphi', 'https://en.wikipedia.org/wiki/Delphi_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('DinkC', 'https://en.wikipedia.org/wiki/Dink_Smallwood#Modification');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('DIBOL', 'https://en.wikipedia.org/wiki/DIBOL');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Dog', 'https://en.wikipedia.org/wiki/Sepandar_Kamvar#.22Dog.22_programming_language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Draco', 'https://en.wikipedia.org/wiki/Draco_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('DRAKON', 'https://en.wikipedia.org/wiki/DRAKON');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Dylan', 'https://en.wikipedia.org/wiki/Dylan_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('DYNAMO', 'https://en.wikipedia.org/wiki/DYNAMO_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('E', 'https://en.wikipedia.org/wiki/E_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('E#', 'https://en.wikipedia.org/wiki/E_Sharp_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Ease', 'https://en.wikipedia.org/wiki/Ease_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Easy PL/I', 'https://en.wikipedia.org/wiki/PL/I');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Easy Programming Language', 'https://en.wikipedia.org/wiki/Easy_Programming_Language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('EASYTRIEVE PLUS', 'https://en.wikipedia.org/wiki/Easytrieve');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ECMAScript', 'https://en.wikipedia.org/wiki/ECMAScript');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Edinburgh IMP', 'https://en.wikipedia.org/wiki/Edinburgh_IMP');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('EGL', 'https://en.wikipedia.org/wiki/EGL_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Eiffel', 'https://en.wikipedia.org/wiki/Eiffel_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ELAN', 'https://en.wikipedia.org/wiki/ELAN_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Elixir', 'https://en.wikipedia.org/wiki/Elixir_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Elm', 'https://en.wikipedia.org/wiki/Elm_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Emacs Lisp', 'https://en.wikipedia.org/wiki/Emacs_Lisp');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Emerald', 'https://en.wikipedia.org/wiki/Emerald_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Epigram', 'https://en.wikipedia.org/wiki/Epigram_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('EPL', 'https://en.wikipedia.org/wiki/Easy_Programming_Language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Erlang', 'https://en.wikipedia.org/wiki/Erlang_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('es', 'https://en.wikipedia.org/wiki/Es_(Unix_shell)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Escher', 'https://en.wikipedia.org/wiki/Escher_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ESPOL', 'https://en.wikipedia.org/wiki/Executive_Systems_Problem_Oriented_Language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Esterel', 'https://en.wikipedia.org/wiki/Esterel');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Etoys', 'https://en.wikipedia.org/wiki/Etoys_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Euclid', 'https://en.wikipedia.org/wiki/Euclid_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Euler', 'https://en.wikipedia.org/wiki/Euler_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Euphoria', 'https://en.wikipedia.org/wiki/Euphoria_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('EusLisp Robot Programming Language', 'https://en.wikipedia.org/wiki/EusLisp_Robot_Programming_Language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('CMS EXEC (EXEC)', 'https://en.wikipedia.org/wiki/CMS_EXEC');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('EXEC 2', 'https://en.wikipedia.org/wiki/EXEC_2');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Executable UML', 'https://en.wikipedia.org/wiki/Executable_UML');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('F', 'https://en.wikipedia.org/wiki/F_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('F#', 'https://en.wikipedia.org/wiki/F_Sharp_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Factor', 'https://en.wikipedia.org/wiki/Factor_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Falcon', 'https://en.wikipedia.org/wiki/Falcon_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Fantom', 'https://en.wikipedia.org/wiki/Fantom_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('FAUST', 'https://en.wikipedia.org/wiki/FAUST_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('FFP', 'https://en.wikipedia.org/wiki/FFP_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Fjölnir', 'https://en.wikipedia.org/wiki/Fj%C3%B6lnir_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('FL', 'https://en.wikipedia.org/wiki/FL_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Flavors', 'https://en.wikipedia.org/wiki/Flavors_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Flex', 'https://en.wikipedia.org/wiki/Flex_(language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('FlooP', 'https://en.wikipedia.org/wiki/BlooP_and_FlooP');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('FLOW-MATIC', 'https://en.wikipedia.org/wiki/FLOW-MATIC');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('FOCAL', 'https://en.wikipedia.org/wiki/FOCAL_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('FOCUS', 'https://en.wikipedia.org/wiki/FOCUS');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('FOIL', 'https://en.wikipedia.org/wiki/FOIL_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('FORMAC', 'https://en.wikipedia.org/wiki/FORMAC_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('@Formula', 'https://en.wikipedia.org/wiki/Formula_language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Forth', 'https://en.wikipedia.org/wiki/Forth_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Fortran – ISO/IEC 1539', 'https://en.wikipedia.org/wiki/Fortran');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Fortress', 'https://en.wikipedia.org/wiki/Fortress_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('FoxBase', 'https://en.wikipedia.org/wiki/FoxBase');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('FoxPro', 'https://en.wikipedia.org/wiki/FoxPro');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('FP', 'https://en.wikipedia.org/wiki/FP_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('FPr', 'https://en.wikipedia.org/wiki/FPr_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Franz Lisp', 'https://en.wikipedia.org/wiki/Franz_Lisp');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Frege', 'https://en.wikipedia.org/wiki/Frege_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('F-Script', 'https://en.wikipedia.org/wiki/F-Script_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('G', 'https://en.wikipedia.org/wiki/G_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Game Maker Language', 'https://en.wikipedia.org/wiki/GameMaker:_Studio');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('GameMonkey Script', 'https://en.wikipedia.org/wiki/GameMonkey_Script');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('GAMS', 'https://en.wikipedia.org/wiki/General_Algebraic_Modeling_System');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('GAP', 'https://en.wikipedia.org/wiki/GAP_computer_algebra_system');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('G-code', 'https://en.wikipedia.org/wiki/G-code');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Genie', 'https://en.wikipedia.org/wiki/Genie_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('GDL', 'https://en.wikipedia.org/wiki/Geometric_Description_Language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('GJ', 'https://en.wikipedia.org/wiki/Generic_Java');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('GEORGE', 'https://en.wikipedia.org/wiki/GEORGE_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('GLSL', 'https://en.wikipedia.org/wiki/GLSL');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('GNU E', 'https://en.wikipedia.org/wiki/GNU_E');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('GM', 'https://en.wikipedia.org/wiki/Golden_master');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Go', 'https://en.wikipedia.org/wiki/Go_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Go!', 'https://en.wikipedia.org/wiki/Go!_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('GOAL', 'https://en.wikipedia.org/wiki/Game_Oriented_Assembly_Lisp');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Gödel', 'https://en.wikipedia.org/wiki/G%C3%B6del_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Godiva', 'https://en.wikipedia.org/wiki/Godiva_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Golo', 'https://en.wikipedia.org/wiki/Golo_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('GOM (Good Old Mad)', 'https://en.wikipedia.org/wiki/MAD_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Google Apps Script', 'https://en.wikipedia.org/wiki/Google_Apps_Script');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Gosu', 'https://en.wikipedia.org/wiki/Gosu_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('GOTRAN', 'https://en.wikipedia.org/wiki/IBM_1620#GOTRAN');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('GPSS', 'https://en.wikipedia.org/wiki/GPSS');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('GraphTalk', 'https://en.wikipedia.org/wiki/Computer_Sciences_Corporation');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('GRASS', 'https://en.wikipedia.org/wiki/GRASS_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Groovy', 'https://en.wikipedia.org/wiki/Groovy_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Hack', 'https://en.wikipedia.org/wiki/Hack_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('HAL/S', 'https://en.wikipedia.org/wiki/HAL/S');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Hamilton C shell', 'https://en.wikipedia.org/wiki/Hamilton_C_shell');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Harbour', 'https://en.wikipedia.org/wiki/Harbour_(software)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Hartmann pipelines', 'https://en.wikipedia.org/wiki/Hartmann_pipeline');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Haskell', 'https://en.wikipedia.org/wiki/Haskell_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Haxe', 'https://en.wikipedia.org/wiki/Haxe');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('High Level Assembly', 'https://en.wikipedia.org/wiki/High_Level_Assembly');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('HLSL', 'https://en.wikipedia.org/wiki/High_Level_Shader_Language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Hop', 'https://en.wikipedia.org/wiki/Hop_(software)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Hopscotch', 'https://en.wikipedia.org/wiki/Hopscotch_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Hope', 'https://en.wikipedia.org/wiki/Hope_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Hugo', 'https://en.wikipedia.org/wiki/Hugo_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Hume', 'https://en.wikipedia.org/wiki/Hume_(language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('HyperTalk', 'https://en.wikipedia.org/wiki/HyperTalk');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('IBM Basic assembly language', 'https://en.wikipedia.org/wiki/IBM_Basic_assembly_language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('IBM HAScript', 'https://en.wikipedia.org/wiki/IBM_HAScript');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('IBM Informix-4GL', 'https://en.wikipedia.org/wiki/IBM_Informix-4GL');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('IBM RPG', 'https://en.wikipedia.org/wiki/IBM_RPG');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ICI', 'https://en.wikipedia.org/wiki/ICI_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Icon', 'https://en.wikipedia.org/wiki/Icon_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Id', 'https://en.wikipedia.org/wiki/Id_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('IDL', 'https://en.wikipedia.org/wiki/IDL_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Idris', 'https://en.wikipedia.org/wiki/Idris_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('IMP', 'https://en.wikipedia.org/wiki/IMP_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Inform', 'https://en.wikipedia.org/wiki/Inform');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Io', 'https://en.wikipedia.org/wiki/Io_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Ioke', 'https://en.wikipedia.org/wiki/Ioke_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('IPL', 'https://en.wikipedia.org/wiki/Information_Processing_Language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('IPTSCRAE', 'https://en.wikipedia.org/wiki/IPTSCRAE');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ISLISP', 'https://en.wikipedia.org/wiki/ISLISP');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ISPF', 'https://en.wikipedia.org/wiki/ISPF');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ISWIM', 'https://en.wikipedia.org/wiki/ISWIM');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('J', 'https://en.wikipedia.org/wiki/J_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('J#', 'https://en.wikipedia.org/wiki/J_Sharp');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('J++', 'https://en.wikipedia.org/wiki/Visual_J%2B%2B');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('JADE', 'https://en.wikipedia.org/wiki/JADE_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Jako', 'https://en.wikipedia.org/wiki/Jako_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('JAL', 'https://en.wikipedia.org/wiki/JAL_(compiler)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Janus (concurrent constraint programming language)', 'https://en.wikipedia.org/wiki/Janus_(concurrent_constraint_programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Janus (time-reversible computing programming language)', 'https://en.wikipedia.org/wiki/Janus_(time-reversible_computing_programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('JASS', 'https://en.wikipedia.org/wiki/JASS');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Java', 'https://en.wikipedia.org/wiki/Java_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('JavaScript', 'https://en.wikipedia.org/wiki/JavaScript');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('JCL', 'https://en.wikipedia.org/wiki/Job_Control_Language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('JEAN', 'https://en.wikipedia.org/wiki/JEAN');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Join Java', 'https://en.wikipedia.org/wiki/Join_Java');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('JOSS', 'https://en.wikipedia.org/wiki/JOSS');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Joule', 'https://en.wikipedia.org/wiki/Joule_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('JOVIAL', 'https://en.wikipedia.org/wiki/JOVIAL');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Joy', 'https://en.wikipedia.org/wiki/Joy_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('JScript', 'https://en.wikipedia.org/wiki/JScript');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('JScript .NET', 'https://en.wikipedia.org/wiki/JScript_.NET');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('JavaFX Script', 'https://en.wikipedia.org/wiki/JavaFX_Script');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Julia', 'https://en.wikipedia.org/wiki/Julia_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Jython', 'https://en.wikipedia.org/wiki/Jython');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('K', 'https://en.wikipedia.org/wiki/K_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Kaleidoscope', 'https://en.wikipedia.org/wiki/Kaleidoscope_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Karel', 'https://en.wikipedia.org/wiki/Karel_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Karel++', 'https://en.wikipedia.org/wiki/Karel%2B%2B');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('KEE', 'https://en.wikipedia.org/wiki/IntelliCorp_(Software)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Kixtart', 'https://en.wikipedia.org/wiki/KiXtart');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Klerer-May System', 'https://en.wikipedia.org/wiki/Klerer-May_System');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('KIF', 'https://en.wikipedia.org/wiki/Knowledge_Interchange_Format');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Kojo', 'https://en.wikipedia.org/wiki/Kojo_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Kotlin', 'https://en.wikipedia.org/wiki/Kotlin_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('KRC', 'https://en.wikipedia.org/wiki/Kent_Recursive_Calculator');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('KRL', 'https://en.wikipedia.org/wiki/KRL_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('KUKA Robot Language)', 'https://en.wikipedia.org/wiki/KUKA');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('KRYPTON', 'https://en.wikipedia.org/wiki/KRYPTON');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ksh', 'https://en.wikipedia.org/wiki/Korn_shell');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('L', 'https://en.wikipedia.org/wiki/L_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('L# .NET', 'https://en.wikipedia.org/wiki/L_Sharp');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('LabVIEW', 'https://en.wikipedia.org/wiki/LabVIEW');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Ladder', 'https://en.wikipedia.org/wiki/Ladder_logic');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Lagoona', 'https://en.wikipedia.org/wiki/Lagoona_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('LANSA', 'https://en.wikipedia.org/wiki/LANSA_(development_environment)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Lasso', 'https://en.wikipedia.org/wiki/Lasso_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('LaTeX', 'https://en.wikipedia.org/wiki/LaTeX');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Lava', 'https://en.wikipedia.org/wiki/Lava_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('LC-3', 'https://en.wikipedia.org/wiki/LC-3');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Leda', 'https://en.wikipedia.org/wiki/Leda_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Legoscript', 'https://en.wikipedia.org/wiki/Lego_Mindstorms');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('LIL', 'https://en.wikipedia.org/wiki/Little_Implementation_Language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('LilyPond', 'https://en.wikipedia.org/wiki/LilyPond');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Limbo', 'https://en.wikipedia.org/wiki/Limbo_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Limnor', 'https://en.wikipedia.org/wiki/Limnor');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('LINC', 'https://en.wikipedia.org/wiki/LINC_4GL');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Lingo', 'https://en.wikipedia.org/wiki/Lingo_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('LIS', 'https://en.wikipedia.org/wiki/LIS_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('LISA', 'https://en.wikipedia.org/wiki/Language_for_Instruction_Set_Architecture');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Lisaac', 'https://en.wikipedia.org/wiki/Lisaac');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Lisp – ISO/IEC 13816', 'https://en.wikipedia.org/wiki/Lisp_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Lite-C', 'https://en.wikipedia.org/wiki/Lite-C');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Lithe', 'https://en.wikipedia.org/wiki/Lithe_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Little b', 'https://en.wikipedia.org/wiki/Little_b_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Logo', 'https://en.wikipedia.org/wiki/Logo_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Logtalk', 'https://en.wikipedia.org/wiki/Logtalk');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('LotusScript', 'https://en.wikipedia.org/wiki/LotusScript');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('LPC', 'https://en.wikipedia.org/wiki/LPC_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('LSE', 'https://en.wikipedia.org/wiki/LSE_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('LSL', 'https://en.wikipedia.org/wiki/Linden_Scripting_Language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('LiveCode', 'https://en.wikipedia.org/wiki/LiveCode');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('LiveScript', 'https://en.wikipedia.org/wiki/LiveScript');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Lua', 'https://en.wikipedia.org/wiki/Lua_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Lucid', 'https://en.wikipedia.org/wiki/Lucid_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Lustre', 'https://en.wikipedia.org/wiki/Lustre_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('LYaPAS', 'https://en.wikipedia.org/wiki/LYaPAS');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Lynx', 'https://en.wikipedia.org/wiki/Lynx_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('M2001', 'https://en.wikipedia.org/wiki/M2001');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('MarsCode (programming language)', null);
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('M4', 'https://en.wikipedia.org/wiki/M4_(computer_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('M#', 'https://en.wikipedia.org/wiki/M_Sharp_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Machine code', 'https://en.wikipedia.org/wiki/Machine_code');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('MAD (Michigan Algorithm Decoder)', 'https://en.wikipedia.org/wiki/MAD_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('MAD/I', 'https://en.wikipedia.org/wiki/MAD_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Magik', 'https://en.wikipedia.org/wiki/Magik_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Magma', 'https://en.wikipedia.org/wiki/Magma_computer_algebra_system');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('make', 'https://en.wikipedia.org/wiki/Make_(software)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Maple', 'https://en.wikipedia.org/wiki/Maple_(software)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('MAPPER now part of BIS', 'https://en.wikipedia.org/wiki/MAPPER');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('MARK-IV now VISION:BUILDER', 'https://en.wikipedia.org/wiki/MARK_IV_(software)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Mary', 'https://en.wikipedia.org/wiki/Mary_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('MASM Microsoft Assembly x86', 'https://en.wikipedia.org/wiki/Microsoft_Macro_Assembler');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('MATH-MATIC', 'https://en.wikipedia.org/wiki/MATH-MATIC');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Mathematica', 'https://en.wikipedia.org/wiki/Mathematica');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('MATLAB', 'https://en.wikipedia.org/wiki/MATLAB');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Maxima (see also', 'https://en.wikipedia.org/wiki/Maxima_(software)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Macsyma )', 'https://en.wikipedia.org/wiki/Macsyma');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Max (Max Msp – Graphical Programming Environment)', 'https://en.wikipedia.org/wiki/Max_(software)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('MaxScript internal language 3D Studio Max', 'https://en.wikipedia.org/wiki/Autodesk_3ds_Max');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Maya (MEL)', 'https://en.wikipedia.org/wiki/Maya_Embedded_Language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('MDL', 'https://en.wikipedia.org/wiki/MDL_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Mercury', 'https://en.wikipedia.org/wiki/Mercury_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Mesa', 'https://en.wikipedia.org/wiki/Mesa_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Metacard', 'https://en.wikipedia.org/wiki/Metacard');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Metafont', 'https://en.wikipedia.org/wiki/Metafont');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Microcode', 'https://en.wikipedia.org/wiki/Microassembler');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('MicroScript', 'https://en.wikipedia.org/wiki/MicroScript_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('MIIS', 'https://en.wikipedia.org/wiki/MIIS_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('MillScript', 'https://en.wikipedia.org/wiki/MillScript');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('MIMIC', 'https://en.wikipedia.org/wiki/MIMIC');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Mirah', 'https://en.wikipedia.org/wiki/Mirah_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Miranda', 'https://en.wikipedia.org/wiki/Miranda_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('MIVA Script', 'https://en.wikipedia.org/wiki/MIVA_Script');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ML', 'https://en.wikipedia.org/wiki/ML_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Moby', 'https://en.wikipedia.org/wiki/Moby_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Model 204', 'https://en.wikipedia.org/wiki/Model_204');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Modelica', 'https://en.wikipedia.org/wiki/Modelica');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Modula', 'https://en.wikipedia.org/wiki/Modula');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Modula-2', 'https://en.wikipedia.org/wiki/Modula-2');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Modula-3', 'https://en.wikipedia.org/wiki/Modula-3');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Mohol', 'https://en.wikipedia.org/wiki/Mohol_programming_languages');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('MOO', 'https://en.wikipedia.org/wiki/MOO_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Mortran', 'https://en.wikipedia.org/wiki/Mortran');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Mouse', 'https://en.wikipedia.org/wiki/Mouse_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('MPD', 'https://en.wikipedia.org/wiki/MPD_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('CIL', 'https://en.wikipedia.org/wiki/Common_Intermediate_Language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('MSL', 'https://en.wikipedia.org/wiki/MIRC_scripting_language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('MUMPS', 'https://en.wikipedia.org/wiki/MUMPS');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Mystic Programming Language (MPL)', 'https://en.wikipedia.org/wiki/Mystic_BBS');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('NASM', 'https://en.wikipedia.org/wiki/Netwide_Assembler');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Napier88', 'https://en.wikipedia.org/wiki/Napier88');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Neko', 'https://en.wikipedia.org/wiki/Neko_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Nemerle', 'https://en.wikipedia.org/wiki/Nemerle');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('nesC', 'https://en.wikipedia.org/wiki/NesC');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('NESL', 'https://en.wikipedia.org/wiki/NESL');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Net.Data', 'https://en.wikipedia.org/wiki/Net.Data');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('NetLogo', 'https://en.wikipedia.org/wiki/NetLogo');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('NetRexx', 'https://en.wikipedia.org/wiki/NetRexx');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('NewLISP', 'https://en.wikipedia.org/wiki/NewLISP');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('NEWP', 'https://en.wikipedia.org/wiki/NEWP');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Newspeak', 'https://en.wikipedia.org/wiki/Newspeak_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('NewtonScript', 'https://en.wikipedia.org/wiki/NewtonScript');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('NGL', 'https://en.wikipedia.org/wiki/NGL_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Nial', 'https://en.wikipedia.org/wiki/Nial');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Nice', 'https://en.wikipedia.org/wiki/Nice_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Nickle', 'https://en.wikipedia.org/wiki/Nickle_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Nim', 'https://en.wikipedia.org/wiki/Nim_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('NPL', 'https://en.wikipedia.org/wiki/NORD_Programming_Language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Not eXactly C (NXC)', 'https://en.wikipedia.org/wiki/Not_eXactly_C');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Not Quite C (NQC)', 'https://en.wikipedia.org/wiki/Not_Quite_C');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('NSIS', 'https://en.wikipedia.org/wiki/Nullsoft_Scriptable_Install_System');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Nu', 'https://en.wikipedia.org/wiki/Nu_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('NWScript', 'https://en.wikipedia.org/wiki/NWScript');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('NXT-G', 'https://en.wikipedia.org/wiki/NXT-G');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('o:XML', 'https://en.wikipedia.org/wiki/O:XML');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Oak', 'https://en.wikipedia.org/wiki/Oak_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Oberon', 'https://en.wikipedia.org/wiki/Oberon_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('OBJ2', 'https://en.wikipedia.org/wiki/OBJ2');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Object Lisp', 'https://en.wikipedia.org/wiki/Object_Lisp');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ObjectLOGO', 'https://en.wikipedia.org/wiki/ObjectLOGO');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Object REXX', 'https://en.wikipedia.org/wiki/Object_REXX');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Object Pascal', 'https://en.wikipedia.org/wiki/Object_Pascal');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Objective-C', 'https://en.wikipedia.org/wiki/Objective-C');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Objective-J', 'https://en.wikipedia.org/wiki/Objective-J');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Obliq', 'https://en.wikipedia.org/wiki/Obliq');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('OCaml', 'https://en.wikipedia.org/wiki/OCaml');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('occam', 'https://en.wikipedia.org/wiki/Occam_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('occam-π', 'https://en.wikipedia.org/wiki/Occam-%CF%80');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Octave', 'https://en.wikipedia.org/wiki/GNU_Octave');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('OmniMark', 'https://en.wikipedia.org/wiki/OmniMark');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Onyx', 'https://en.wikipedia.org/wiki/Onyx_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Opa', 'https://en.wikipedia.org/wiki/Opa_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Opal', 'https://en.wikipedia.org/wiki/Opal_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('OpenCL', 'https://en.wikipedia.org/wiki/OpenCL');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('OpenEdge ABL', 'https://en.wikipedia.org/wiki/OpenEdge_Advanced_Business_Language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('OPL', 'https://en.wikipedia.org/wiki/Open_Programming_Language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('OPS5', 'https://en.wikipedia.org/wiki/OPS5');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('OptimJ', 'https://en.wikipedia.org/wiki/OptimJ');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Orc', 'https://en.wikipedia.org/wiki/Orc_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ORCA/Modula-2', 'https://en.wikipedia.org/wiki/ORCA/Modula-2');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Oriel', 'https://en.wikipedia.org/wiki/Oriel_(scripting_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Orwell', 'https://en.wikipedia.org/wiki/Orwell_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Oxygene', 'https://en.wikipedia.org/wiki/Oxygene_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Oz', 'https://en.wikipedia.org/wiki/Oz_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('P′′', 'https://en.wikipedia.org/wiki/P%E2%80%B2%E2%80%B2');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('P#', 'https://en.wikipedia.org/wiki/P_Sharp');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ParaSail (programming language)', 'https://en.wikipedia.org/wiki/ParaSail_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('PARI/GP', 'https://en.wikipedia.org/wiki/PARI/GP');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Pascal – ISO 7185', 'https://en.wikipedia.org/wiki/Pascal_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('PCASTL', 'https://en.wikipedia.org/wiki/PCASTL');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('PCF', 'https://en.wikipedia.org/wiki/Programming_language_for_Computable_Functions');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('PEARL', 'https://en.wikipedia.org/wiki/PEARL_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('PeopleCode', 'https://en.wikipedia.org/wiki/PeopleCode');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Perl', 'https://en.wikipedia.org/wiki/Perl');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('PDL', 'https://en.wikipedia.org/wiki/Perl_Data_Language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Perl6', 'https://en.wikipedia.org/wiki/Perl6');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Pharo', 'https://en.wikipedia.org/wiki/Pharo');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('PHP', 'https://en.wikipedia.org/wiki/PHP');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Phrogram', 'https://en.wikipedia.org/wiki/Phrogram');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Pico', 'https://en.wikipedia.org/wiki/Pico_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Picolisp', 'https://en.wikipedia.org/wiki/Picolisp');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Pict', 'https://en.wikipedia.org/wiki/Pict_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Pike', 'https://en.wikipedia.org/wiki/Pike_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('PIKT', 'https://en.wikipedia.org/wiki/PIKT');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('PILOT', 'https://en.wikipedia.org/wiki/PILOT');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Pipelines', 'https://en.wikipedia.org/wiki/Hartmann_pipeline');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Pizza', 'https://en.wikipedia.org/wiki/Pizza_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('PL-11', 'https://en.wikipedia.org/wiki/PL-11');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('PL/0', 'https://en.wikipedia.org/wiki/PL/0');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('PL/B', 'https://en.wikipedia.org/wiki/Programming_Language_for_Business');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('PL/C', 'https://en.wikipedia.org/wiki/PL/C');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('PL/I – ISO 6160', 'https://en.wikipedia.org/wiki/PL/I');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('PL/M', 'https://en.wikipedia.org/wiki/PL/M');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('PL/P', 'https://en.wikipedia.org/wiki/PL/P');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('PL/SQL', 'https://en.wikipedia.org/wiki/PL/SQL');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('PL360', 'https://en.wikipedia.org/wiki/PL360');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('PLANC', 'https://en.wikipedia.org/wiki/PLANC');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Plankalkül', 'https://en.wikipedia.org/wiki/Plankalk%C3%BCl');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Planner', 'https://en.wikipedia.org/wiki/Planner_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('PLEX', 'https://en.wikipedia.org/wiki/PLEX_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('PLEXIL', 'https://en.wikipedia.org/wiki/PLEXIL');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Plus', 'https://en.wikipedia.org/wiki/Plus_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('POP-11', 'https://en.wikipedia.org/wiki/POP-11');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('PostScript', 'https://en.wikipedia.org/wiki/PostScript');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('PortablE', 'https://en.wikipedia.org/wiki/Amiga_E#PortablE');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Powerhouse', 'https://en.wikipedia.org/wiki/Powerhouse_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('PowerBuilder – 4GL GUI applcation generator from Sybase', 'https://en.wikipedia.org/wiki/PowerBuilder');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('PowerShell', 'https://en.wikipedia.org/wiki/PowerShell');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('PPL', 'https://en.wikipedia.org/wiki/Polymorphic_Programming_Language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Processing', 'https://en.wikipedia.org/wiki/Processing_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Processing.js', 'https://en.wikipedia.org/wiki/Processing.js');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Prograph', 'https://en.wikipedia.org/wiki/Prograph');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('PROIV', 'https://en.wikipedia.org/wiki/PROIV');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Prolog', 'https://en.wikipedia.org/wiki/Prolog');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('PROMAL', 'https://en.wikipedia.org/wiki/PROMAL');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Promela', 'https://en.wikipedia.org/wiki/Promela');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('PROSE modeling language', 'https://en.wikipedia.org/wiki/PROSE_modeling_language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('PROTEL', 'https://en.wikipedia.org/wiki/Protel');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ProvideX', 'https://en.wikipedia.org/wiki/ProvideX');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Pro*C', 'https://en.wikipedia.org/wiki/Pro*C');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Pure', 'https://en.wikipedia.org/wiki/Pure_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Python', 'https://en.wikipedia.org/wiki/Python_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Q (equational programming language)', 'https://en.wikipedia.org/wiki/Q_(equational_programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Q (programming language from Kx Systems)', 'https://en.wikipedia.org/wiki/Q_(programming_language_from_Kx_Systems)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Qalb', 'https://en.wikipedia.org/wiki/Qalb_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('QtScript', 'https://en.wikipedia.org/wiki/QtScript');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('QuakeC', 'https://en.wikipedia.org/wiki/QuakeC');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('QPL', 'https://en.wikipedia.org/wiki/Quantum_programming');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('R', 'https://en.wikipedia.org/wiki/R_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('R++', 'https://en.wikipedia.org/wiki/R%2B%2B');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Racket', 'https://en.wikipedia.org/wiki/Racket_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('RAPID', 'https://en.wikipedia.org/wiki/RAPID');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Rapira', 'https://en.wikipedia.org/wiki/Rapira');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Ratfiv', 'https://en.wikipedia.org/wiki/Ratfiv');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Ratfor', 'https://en.wikipedia.org/wiki/Ratfor');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('rc', 'https://en.wikipedia.org/wiki/Rc');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('REBOL', 'https://en.wikipedia.org/wiki/REBOL');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Red', 'https://en.wikipedia.org/wiki/Red_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Redcode', 'https://en.wikipedia.org/wiki/Core_War');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('REFAL', 'https://en.wikipedia.org/wiki/REFAL');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Reia', 'https://en.wikipedia.org/wiki/Reia_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Revolution', 'https://en.wikipedia.org/wiki/Revolution_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('REXX', 'https://en.wikipedia.org/wiki/REXX');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Rlab', 'https://en.wikipedia.org/wiki/Rlab');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ROOP', 'https://en.wikipedia.org/wiki/ROOP_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('RPG', 'https://en.wikipedia.org/wiki/IBM_RPG');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('RPL', 'https://en.wikipedia.org/wiki/RPL_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('RSL', 'https://en.wikipedia.org/wiki/Robot_Battle#Robot_scripting_language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('RTL/2', 'https://en.wikipedia.org/wiki/RTL/2');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Ruby', 'https://en.wikipedia.org/wiki/Ruby_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('RuneScript', 'https://en.wikipedia.org/wiki/RuneScape#History_and_development');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Rust', 'https://en.wikipedia.org/wiki/Rust_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('S', 'https://en.wikipedia.org/wiki/S_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('S2', 'https://en.wikipedia.org/wiki/S2_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('S3', 'https://en.wikipedia.org/wiki/S3_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('S-Lang', 'https://en.wikipedia.org/wiki/S-Lang_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('S-PLUS', 'https://en.wikipedia.org/wiki/S-PLUS');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('SA-C', 'https://en.wikipedia.org/wiki/SA-C_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('SabreTalk', 'https://en.wikipedia.org/wiki/SabreTalk');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('SAIL', 'https://en.wikipedia.org/wiki/SAIL_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('SALSA', 'https://en.wikipedia.org/wiki/SALSA_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('SAM76', 'https://en.wikipedia.org/wiki/SAM76');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('SAS', 'https://en.wikipedia.org/wiki/SAS_System');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('SASL', 'https://en.wikipedia.org/wiki/SASL_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Sather', 'https://en.wikipedia.org/wiki/Sather');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Sawzall', 'https://en.wikipedia.org/wiki/Sawzall_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('SBL', 'https://en.wikipedia.org/wiki/Superbase_database');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Scala', 'https://en.wikipedia.org/wiki/Scala_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Scheme', 'https://en.wikipedia.org/wiki/Scheme_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Scilab', 'https://en.wikipedia.org/wiki/Scilab');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Scratch', 'https://en.wikipedia.org/wiki/Scratch_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Script.NET', 'https://en.wikipedia.org/wiki/Script.NET');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Sed', 'https://en.wikipedia.org/wiki/Sed');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Seed7', 'https://en.wikipedia.org/wiki/Seed7');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Self', 'https://en.wikipedia.org/wiki/Self_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('SenseTalk', 'https://en.wikipedia.org/wiki/SenseTalk');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('SequenceL', 'https://en.wikipedia.org/wiki/SequenceL');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('SETL', 'https://en.wikipedia.org/wiki/SETL');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('SIMPOL', 'https://en.wikipedia.org/wiki/Superbase_database#History');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('SIGNAL', 'https://en.wikipedia.org/wiki/SIGNAL_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('SiMPLE', 'https://en.wikipedia.org/wiki/SiMPLE');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('SIMSCRIPT', 'https://en.wikipedia.org/wiki/SIMSCRIPT');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Simula', 'https://en.wikipedia.org/wiki/Simula');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Simulink', 'https://en.wikipedia.org/wiki/Simulink');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('SISAL', 'https://en.wikipedia.org/wiki/SISAL');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('SLIP', 'https://en.wikipedia.org/wiki/SLIP_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('SMALL', 'https://en.wikipedia.org/wiki/SMALL');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Smalltalk', 'https://en.wikipedia.org/wiki/Smalltalk');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Small Basic', 'https://en.wikipedia.org/wiki/Microsoft_Small_Basic');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('SML', 'https://en.wikipedia.org/wiki/Standard_ML');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Snap!', 'https://en.wikipedia.org/wiki/Snap!_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('SNOBOL (', 'https://en.wikipedia.org/wiki/SNOBOL');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('SPITBOL )', 'https://en.wikipedia.org/wiki/SPITBOL_compiler');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Snowball', 'https://en.wikipedia.org/wiki/Snowball_programming_language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('SOL', 'https://en.wikipedia.org/wiki/Secure_Operations_Language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Span', 'https://en.wikipedia.org/wiki/Span_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('SPARK', 'https://en.wikipedia.org/wiki/SPARK_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Speedcode', 'https://en.wikipedia.org/wiki/Speedcoding');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('SPIN', 'https://en.wikipedia.org/wiki/Parallax_Propeller');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('SP/k', 'https://en.wikipedia.org/wiki/SP/k');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('SPS', 'https://en.wikipedia.org/wiki/IBM_1401_Symbolic_Programming_System');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('SQR', 'https://en.wikipedia.org/wiki/SQR');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Squeak', 'https://en.wikipedia.org/wiki/Squeak');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Squirrel', 'https://en.wikipedia.org/wiki/Squirrel_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('SR', 'https://en.wikipedia.org/wiki/SR_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('S/SL', 'https://en.wikipedia.org/wiki/S/SL_programming_language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Stackless Python', 'https://en.wikipedia.org/wiki/Stackless_Python');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Starlogo', 'https://en.wikipedia.org/wiki/Starlogo');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Strand', 'https://en.wikipedia.org/wiki/Strand_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Stata', 'https://en.wikipedia.org/wiki/Stata');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Stateflow', 'https://en.wikipedia.org/wiki/Stateflow');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Subtext', 'https://en.wikipedia.org/wiki/Subtext_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('SuperCollider', 'https://en.wikipedia.org/wiki/SuperCollider');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('SuperTalk', 'https://en.wikipedia.org/wiki/SuperTalk');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Swift (parallel scripting language)', 'https://en.wikipedia.org/wiki/Swift_(parallel_scripting_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('SYMPL', 'https://en.wikipedia.org/wiki/SYMPL');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('SyncCharts', 'https://en.wikipedia.org/wiki/SyncCharts');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('SystemVerilog', 'https://en.wikipedia.org/wiki/SystemVerilog');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('T', 'https://en.wikipedia.org/wiki/T_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('TACL', 'https://en.wikipedia.org/wiki/TACL');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('TACPOL', 'https://en.wikipedia.org/wiki/TACPOL_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('TADS', 'https://en.wikipedia.org/wiki/TADS');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('TAL', 'https://en.wikipedia.org/wiki/Transaction_Application_Language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Tcl', 'https://en.wikipedia.org/wiki/Tcl');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Tea', 'https://en.wikipedia.org/wiki/Tea_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('TECO', 'https://en.wikipedia.org/wiki/Text_Editor_and_Corrector');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('TELCOMP', 'https://en.wikipedia.org/wiki/TELCOMP');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('TeX', 'https://en.wikipedia.org/wiki/TeX');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('TEX', 'https://en.wikipedia.org/wiki/Text_Executive_Programming_Language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('TIE', 'https://en.wikipedia.org/wiki/Tensilica_Instruction_Extension');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Timber', 'https://en.wikipedia.org/wiki/Timber_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('TMG , compiler-compiler', 'https://en.wikipedia.org/wiki/TMG_(language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Tom', 'https://en.wikipedia.org/wiki/Tom_(pattern_matching_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('TOM', 'https://en.wikipedia.org/wiki/TOM_(object-oriented_programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('TouchDevelop', 'https://en.wikipedia.org/wiki/TouchDevelop');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Topspeed', 'https://en.wikipedia.org/wiki/Clarion_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('TPU', 'https://en.wikipedia.org/wiki/Text_Processing_Utility');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Trac', 'https://en.wikipedia.org/wiki/TRAC_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('TTM', 'https://en.wikipedia.org/wiki/TTM_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('T-SQL', 'https://en.wikipedia.org/wiki/Transact-SQL');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('TTCN', 'https://en.wikipedia.org/wiki/TTCN');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Turing', 'https://en.wikipedia.org/wiki/Turing_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('TUTOR', 'https://en.wikipedia.org/wiki/TUTOR_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('TXL', 'https://en.wikipedia.org/wiki/TXL_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('TypeScript', 'https://en.wikipedia.org/wiki/TypeScript');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Turbo C++', 'https://en.wikipedia.org/wiki/Turbo_C%2B%2B');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Ubercode', 'https://en.wikipedia.org/wiki/Ubercode');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('UCSD Pascal', 'https://en.wikipedia.org/wiki/UCSD_Pascal');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Umple', 'https://en.wikipedia.org/wiki/Umple');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Unicon', 'https://en.wikipedia.org/wiki/Unicon_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Uniface', 'https://en.wikipedia.org/wiki/Uniface_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('UNITY', 'https://en.wikipedia.org/wiki/UNITY_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Unix shell', 'https://en.wikipedia.org/wiki/Unix_shell');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('UnrealScript', 'https://en.wikipedia.org/wiki/UnrealScript');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Vala', 'https://en.wikipedia.org/wiki/Vala_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Visual DataFlex', 'https://en.wikipedia.org/wiki/Visual_DataFlex');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Visual DialogScript', 'https://en.wikipedia.org/wiki/Visual_DialogScript');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Visual Fortran', 'https://en.wikipedia.org/wiki/Visual_Fortran');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Visual FoxPro', 'https://en.wikipedia.org/wiki/Visual_FoxPro');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Visual J++', 'https://en.wikipedia.org/wiki/Visual_J%2B%2B');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Visual J#', 'https://en.wikipedia.org/wiki/Visual_J');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Visual Objects', 'https://en.wikipedia.org/wiki/Visual_Objects');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Visual Prolog', 'https://en.wikipedia.org/wiki/Visual_Prolog');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('VSXu', 'https://en.wikipedia.org/wiki/VSXu');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('vvvv', 'https://en.wikipedia.org/wiki/Vvvv');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('WATFIV, WATFOR', 'https://en.wikipedia.org/wiki/WATFIV_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('WebDNA', 'https://en.wikipedia.org/wiki/WebDNA');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('WebQL', 'https://en.wikipedia.org/wiki/WebQL');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Whiley', 'https://en.wikipedia.org/wiki/Whiley_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Windows PowerShell', 'https://en.wikipedia.org/wiki/Windows_PowerShell');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Winbatch', 'https://en.wikipedia.org/wiki/Winbatch');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Wolfram Language', 'https://en.wikipedia.org/wiki/Wolfram_Language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Wyvern', 'https://en.wikipedia.org/wiki/Wyvern_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('X++', 'https://en.wikipedia.org/wiki/Microsoft_Dynamics_AX');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('X#', 'https://en.wikipedia.org/wiki/X_Sharp_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('X10', 'https://en.wikipedia.org/wiki/X10_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('XBL', 'https://en.wikipedia.org/wiki/XBL');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('XC (exploits', 'https://en.wikipedia.org/wiki/XC_Programming_Language');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('XMOS architecture )', 'https://en.wikipedia.org/wiki/XCore_XS1');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('xHarbour', 'https://en.wikipedia.org/wiki/XHarbour');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('XL', 'https://en.wikipedia.org/wiki/XL_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Xojo', 'https://en.wikipedia.org/wiki/Xojo');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('XOTcl', 'https://en.wikipedia.org/wiki/XOTcl');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('XPL', 'https://en.wikipedia.org/wiki/XPL');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('XPL0', 'https://en.wikipedia.org/wiki/XPL0');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('XQuery', 'https://en.wikipedia.org/wiki/XQuery');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('XSB', 'https://en.wikipedia.org/wiki/XSB');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('XSLT – see', 'https://en.wikipedia.org/wiki/XSL_Transformations');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('XPath', 'https://en.wikipedia.org/wiki/XPath');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Xtend', 'https://en.wikipedia.org/wiki/Xtend');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Yorick', 'https://en.wikipedia.org/wiki/Yorick_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('YQL', 'https://en.wikipedia.org/wiki/YQL_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Z notation', 'https://en.wikipedia.org/wiki/Z_notation');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Zeno', 'https://en.wikipedia.org/wiki/Zeno_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ZOPL', 'https://en.wikipedia.org/wiki/ZOPL');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Zsh', 'https://en.wikipedia.org/wiki/Z_shell');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('ZPL', 'https://en.wikipedia.org/wiki/ZPL_(programming_language)');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('C++', 'wikipedia.org/c++');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('C#', 'wikipedia.org/c#');
INSERT INTO test.programming_languages (name, wikipedia_url) VALUES ('Swift', 'wiki.org/swift');